'''
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

'''
Algorithm:
1. XOR all characters in s and t.
2. You will be left with the extra char
'''
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        xor = 0
        for c in s:
            xor = xor^ord(c)
        for c in t:
            xor = xor^ord(c)
        xor = xor^0
        
        return chr(xor)